web/router.ex
defmodule IotData.Router do
  use IotData.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug IotData.Plugs.Auth, repo: IotData.Repo
    plug IotData.Plugs.Locale
  end

  pipeline :login_required do
    plug IotData.Plugs.Session
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IotData do
    pipe_through :browser

    get "/", PageController, :index
    get "/register", UserController, :new
    post "/register", UserController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
  end

  scope "/", IotData do
    pipe_through :browser
    pipe_through :login_required

    get "/account", UserController, :show
    get "/account/edit", UserController, :edit
    put "/account/edit", UserController, :update
    put "/account/generate_api_key", UserController, :generate_api_key
    resources "/feeds", FeedController
    put "/feeds/:id/generate_api_key", FeedController, :generate_api_key
    get "/feeds/:feed_id/export", MeasureController, :export
    resources "/triggers", TriggerController
    resources "/email_actions", EmailActionController
  end

  scope "/api", IotData do
    pipe_through :api

    get "/feeds/:feed_id/data", MeasureController, :index
    post "/feeds", MeasureController, :create
  end
end

web/views/layout_view.ex
defmodule IotData.LayoutView do
  use IotData.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=feed-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello IotData!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/epoch/0.8.4/epoch.min.css">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= page_path(@conn, :index) %>">IoT Data</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            <%= if @current_user do %>
              <li>
                <a href="<%= feed_path(@conn, :index) %>"><%= gettext "Feeds" %> <span class="sr-only">(current)</span></a>
              </li>
              <li>
                <a href="<%= trigger_path(@conn, :index) %>"><%= gettext "Triggers" %> <span class="sr-only">(current)</span></a>
              </li>
              <li>
                <a href="<%= email_action_path(@conn, :index) %>"><%= gettext "Email" %> <span class="sr-only">(current)</span></a>
              </li>
            <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <%= if @current_user do %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= @current_user.username %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link gettext("My account"), to: user_path(@conn, :show) %>
                  </li>
                  <li>
                    <%= link gettext("Edit account"), to: user_path(@conn, :edit) %>
                  </li>
                  <li>
                    <%= link gettext("Sign out"), to: session_path(@conn, :delete) %>
                  </li>
                </ul>
              </li>
              <% else %>
              <li>
                <a href="<%= user_path(@conn, :new) %>"><%= gettext "Sign up" %></a>
              </li>
              <li>
                <a href="<%= session_path(@conn, :new) %>"><%= gettext "Sign in" %></a>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <%= if @current_user do %>
    <script>
      window.api_key = '<%= @current_user.api_key %>'
    </script>
    <% end %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>