web/router.ex
defmodule IotData.Router do
  use IotData.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug IotData.Plugs.Auth, repo: IotData.Repo
    plug IotData.Plugs.Locale
  end

  pipeline :login_required do
    plug IotData.Plugs.Session
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IotData do
    pipe_through :browser

    get "/", PageController, :index
    get "/register", UserController, :new
    post "/register", UserController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
  end

  scope "/", IotData do
    pipe_through :browser
    pipe_through :login_required

    get "/account", UserController, :show
    get "/account/edit", UserController, :edit
    put "/account/edit", UserController, :update
    put "/account/generate_api_key", UserController, :generate_api_key
    resources "/feeds", FeedController
    put "/feeds/:id/generate_api_key", FeedController, :generate_api_key
    get "/feeds/:feed_id/export", MeasureController, :export
    resources "/triggers", TriggerController
    resources "/email_actions", EmailActionController
  end

  scope "/api", IotData do
    pipe_through :api

    get "/feeds/:feed_id/data", MeasureController, :index
    post "/feeds", MeasureController, :create
  end
end

web/models/feed.ex
defmodule IotData.Feed do
  use IotData.Web, :model

  schema "feeds" do
    field :name, :string
    field :description, :string
    field :latitude, :float
    field :longitude, :float
    field :api_key, :string

    belongs_to :user, IotData.User
    has_many :measures, IotData.Measure

    timestamps
  end

  @required_fields ~w(name user_id)
  @optional_fields ~w(description latitude longitude)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """

  def create_changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> foreign_key_constraint(:user_id)
    |> put_api_key
  end

  def edit_changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> foreign_key_constraint(:user_id)
  end

  def generate_api_key do
    Ecto.UUID.generate |> String.replace("-", "")
  end

  defp put_api_key(changeset) do
    if changeset.valid? do
      changeset |> put_change(:api_key, generate_api_key)
    else
      changeset
    end
  end
end

web/controllers/feed_controller.ex
defmodule IotData.FeedController do
  use IotData.Web, :controller

  alias IotData.Feed

  plug :scrub_params, "feed" when action in [:create, :update]
  plug :check_ownership when action in [:show, :edit, :update, :generate_api_key]

  def index(conn, _params) do
    user = conn.assigns[:current_user]
    feeds = Repo.all from d in Feed, where: d.user_id == ^user.id
    render(conn, "index.html", feeds: feeds)
  end

  def new(conn, _params) do
    changeset = Feed.create_changeset(%Feed{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"feed" => feed_params}) do
    user = conn.assigns[:current_user]
    changeset = Feed.create_changeset(%Feed{}, Map.put(feed_params, "user_id", user.id))

    case Repo.insert(changeset) do
      {:ok, _feed} ->
        conn
        |> put_flash(:info, gettext("Feed created successfully"))
        |> redirect(to: feed_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    feed = Repo.get!(Feed, id)
    if conn.port in [80, 443] do
      port = ""
    else
      port = ":#{conn.port}"
    end
    render(conn, "show.html", feed: feed, url: "#{conn.scheme}://#{conn.host}#{port}")
  end

  def edit(conn, %{"id" => id}) do
    feed = Repo.get!(Feed, id)
    changeset = Feed.edit_changeset(feed)
    render(conn, "edit.html", feed: feed, changeset: changeset)
  end

  def update(conn, %{"id" => id, "feed" => feed_params}) do
    feed = Repo.get!(Feed, id)
    user = conn.assigns[:current_user]
    changeset = Feed.edit_changeset(feed, Map.put(feed_params, "user_id", user.id))

    case Repo.update(changeset) do
      {:ok, feed} ->
        conn
        |> put_flash(:info, gettext("Feed updated successfully"))
        |> redirect(to: feed_path(conn, :show, feed))
      {:error, changeset} ->
        render(conn, "edit.html", feed: feed, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    feed = Repo.get!(Feed, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(feed)

    conn
    |> put_flash(:info, gettext("Feed deleted successfully"))
    |> redirect(to: feed_path(conn, :index))
  end

  def generate_api_key(conn, %{"id" => id}) do
    feed = Repo.get!(Feed, id)
    changeset = Ecto.Changeset.change(feed, api_key: Feed.generate_api_key)
    Repo.update(changeset)
    redirect(conn, to: feed_path(conn, :show, feed))
  end

  defp check_ownership(conn, _opts) do
    user = conn.assigns[:current_user]
    feed = Repo.get!(Feed, conn.params["id"])
    if feed.user_id == user.id do
      conn
    else
      conn
      |> redirect(to: feed_path(conn, :index))
    end
  end
end

web/views/feed_view.ex
defmodule IotData.FeedView do
  use IotData.Web, :view
end

web/templates/feed/edit.html.eex
<h2><%= gettext "Edit feed" %></h2>

<%= render "form.html", changeset: @changeset,
                        action: feed_path(@conn, :update, @feed) %>

<%= link gettext("Back"), to: feed_path(@conn, :index) %>

web/templates/feed/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= gettext "Oops, something went wrong! Please check the errors below." %></p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :latitude, class: "control-label" %>
    <%= number_input f, :latitude, step: "any", class: "form-control" %>
    <%= error_tag f, :latitude %>
  </div>

  <div class="form-group">
    <%= label f, :longitude, class: "control-label" %>
    <%= number_input f, :longitude, step: "any", class: "form-control" %>
    <%= error_tag f, :longitude %>
  </div>

  <div class="form-group">
    <%= submit gettext("Submit"), class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/feed/index.html.eex
<h2><%= gettext "Listing feeds" %></h2>

<table class="table">
  <thead>
    <tr>
      <th><%= gettext "Name" %></th>
      <th><%= gettext "Description" %></th>
      <th><%= gettext "Latitude" %></th>
      <th><%= gettext "Longitude" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for feed <- @feeds do %>
    <tr>
      <td><%= feed.name %></td>
      <td><%= feed.description %></td>
      <td><%= feed.latitude %></td>
      <td><%= feed.longitude %></td>

      <td class="text-right">
        <%= link gettext("Show"), to: feed_path(@conn, :show, feed), class: "btn btn-default btn-xs" %>
        <%= link gettext("Edit"), to: feed_path(@conn, :edit, feed), class: "btn btn-default btn-xs" %>
        <%= link gettext("Delete"), to: feed_path(@conn, :delete, feed), method: :delete, data: [confirm: gettext("Are you sure?")], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link gettext("New feed"), to: feed_path(@conn, :new) %>

web/templates/feed/new.html.eex
<h2><%= gettext "New feed" %></h2>

<%= render "form.html", changeset: @changeset,
                        action: feed_path(@conn, :create) %>

<%= link gettext("Back"), to: feed_path(@conn, :index) %>

web/templates/feed/show.html.eex
<div class="col-md-6">
  <h2>
    <%= @feed.name %>
    <%= link gettext("Edit"), to: feed_path(@conn, :edit, @feed), class: "btn btn-primary btn-xs" %>
    <%= link gettext("Back"), to: feed_path(@conn, :index), class: "btn btn-default btn-xs" %>
    <%= link gettext("Export"), to: measure_path(@conn, :export, @feed), class: "btn btn-default btn-xs" %>
  </h2>
  <ul style="list-style: none">
    <li>
      <strong><%= gettext "Description" %>:</strong>
      <%= @feed.description %>
    </li>

    <li>
      <strong><%= gettext "Latitude" %>:</strong>
      <%= @feed.latitude %>
    </li>

    <li>
      <strong><%= gettext "Longitude" %>:</strong>
      <%= @feed.longitude %>
    </li>

    <li>
      <strong><%= gettext "API Key" %>:</strong>
      <%= @feed.api_key %>
      <br>
      <%= link gettext("Generate new API Key"), to: feed_path(@conn, :generate_api_key, @feed.id), method: "put", class: "btn btn-warning btn-xs" %>
    </li>
  </ul>

  <div id="chart" class="epoch" style="width: 100%; height: 400px">
  </div>
</div>
<div class="col-md-6">
  <h3><%= gettext "Try the API" %></h3>
  <h4><%= gettext "Push a value" %></h4>
  <h5><%= gettext "Using" %> Curl</h5>
  <pre>
curl -H "X-Api-Key: <%= @feed.api_key %>" -H "Content-Type: application/json" -d '{"value": 55}' <%= @url <> measure_path(@conn, :create) %>
  </pre>
  <h5><%= gettext "Using" %> <a href="http://httpie.org">httpie</a></h5>
  <pre>
echo '{"value": 55}' | http post <%= @url <> measure_path(@conn, :create) %> X-Api-Key:<%= @feed.api_key %>
  </pre>
  <h4><%= gettext "Get values" %></h4>
  <h5><%= gettext "Using" %> Curl</h5>
  <pre>
curl -H "X-Api-Key: <%= @feed.api_key %>" -H "Content-Type: application/json" <%= @url <> measure_path(@conn, :index, @feed.id) %>
  </pre>
  <h5><%= gettext "Using" %> <a href="http://httpie.org">httpie</a></h5>
  <pre>
http get <%= @url <> measure_path(@conn, :index, @feed.id) %> X-Api-Key:<%= @feed.api_key %>
  </pre>
</div>
<script>
  window.feed_id = <%= @feed.id %>
  window.feed_api_key = '<%= @feed.api_key %>'
</script>